//! Writes `src/Tables.mw` and `src/Cases.mw` for sha2.
//!
//! ```text
//! cargo run --release -- <package root>
//! ```
//!
//! * **Tables** -- the crate's round constants and initial states.
//! * **Cases** -- messages, with the digest each SHA-2 function gives them,
//!   hashed whole and in pieces.
//!
//! The functions are ported by hand into `src/`, and the crate's portable
//! implementation is fingerprinted.

#[allow(dead_code, clippy::all)]
mod consts {
    include!(concat!(env!("OUT_DIR"), "/consts.rs"));
}

use sha2::{Digest, Sha224, Sha256, Sha384, Sha512, Sha512_224, Sha512_256};
use std::fmt::Write as _;
use std::path::PathBuf;

/// The crate version pinned in `Cargo.toml`.
const UPSTREAM_VERSION: &str = "0.10.9";

/// The fingerprint of the crate's source, which `src/` ports.
const SOURCES: u64 = 0x2bd5_58dc_6b14_888a;

fn main() {
    let root = PathBuf::from(std::env::args().nth(1).unwrap_or_else(|| "../..".into()));

    let print = fingerprint(include_str!(concat!(env!("OUT_DIR"), "/sources.rs.txt")));
    if print != SOURCES {
        eprintln!(
            "error: sha2 is not the version src/ ports.\n\
             Compare its source in {} with the previous version, carry any change\n\
             into src/, then set SOURCES in scripts/generate/src/main.rs to\n\
             {print:#x}",
            env!("UPSTREAM_DIR")
        );
        std::process::exit(1);
    }

    let tables = tables();
    let path = root.join("src/Tables.mw");
    std::fs::write(&path, &tables).unwrap();
    eprintln!("wrote {} ({} bytes)", path.display(), tables.len());

    let cases = cases();
    let path = root.join("src/Cases.mw");
    std::fs::write(&path, &cases).unwrap();
    eprintln!("wrote {} ({} bytes)", path.display(), cases.len());
}

/// FNV-1a: stable across builds, which `DefaultHasher` does not promise.
fn fingerprint(text: &str) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in text.bytes() {
        h ^= u64::from(b);
        h = h.wrapping_mul(0x0100_0000_01b3);
    }
    h
}

// --- encoding -----------------------------------------------------------------------

/// A number as `digits` base-64 digits, most significant first, each digit the
/// character `'0' + d`: `'0'` to `'o'`, one contiguous run of ASCII.
fn digits(out: &mut String, value: u64, digits: u32) {
    assert!(
        value < 1 << (6 * digits),
        "{value} does not fit in {digits} digits"
    );
    for k in (0..digits).rev() {
        out.push(char::from(b'0' + ((value >> (6 * k)) & 63) as u8));
    }
}

/// A string, as its length in bytes (3 digits) and then its bytes.
fn text(out: &mut String, s: &str) {
    digits(out, s.len() as u64, 3);
    out.push_str(s);
}

/// Bytes, as a string of their hex digits.
fn bytes(out: &mut String, b: &[u8]) {
    let hex: String = b.iter().map(|x| format!("{x:02x}")).collect();
    text(out, &hex);
}

/// `text` as one Meadow string literal, broken with `\`-newline every `width`
/// characters. Only printable ASCII is written raw; a space that would start a
/// line is `\x20`, since a continuation drops leading whitespace.
fn long_literal(text: &str, width: usize) -> String {
    let mut out = String::with_capacity(text.len() + text.len() / width * 4 + 2);
    out.push('"');
    for (i, c) in text.chars().enumerate() {
        let line_start = i > 0 && i % width == 0;
        if line_start {
            out.push_str("\\\n    ");
        }
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '$' => out.push_str("\\$"),
            ' ' if line_start => out.push_str("\\x20"),
            ' '..='~' => out.push(c),
            _ => {
                let _ = write!(out, "\\u{{{:X}}}", u32::from(c));
            }
        }
    }
    out.push('"');
    out
}

const HEADER: &str = "\
-- Copyright RustCrypto Developers, and the Meadow port's authors.
-- Dual-licensed under Apache-2.0 or MIT: see COPYRIGHT.";

// --- tables -------------------------------------------------------------------------

fn words32(ws: &[u32]) -> String {
    ws.iter().map(|w| format!("{w:08x}")).collect()
}

fn words64(ws: &[u64]) -> String {
    ws.iter().map(|w| format!("{w:016x}")).collect()
}

fn tables() -> String {
    use consts::*;
    let mut out = String::new();
    let _ = writeln!(
        out,
        "-- GENERATED by scripts/generate.sh from sha2 {UPSTREAM_VERSION}.
-- Do not edit: run the script again instead.
--
-- The constants of FIPS 180-4, as the crate has them: words written as hex
-- digits, 8 to a 32-bit word and 16 to a 64-bit one.
--
{HEADER}
"
    );
    for (name, doc, value) in [
        (
            "k32",
            "The SHA-256 family's 64 round constants.",
            words32(&K32),
        ),
        (
            "k64",
            "The SHA-512 family's 80 round constants.",
            words64(&K64),
        ),
        ("h224", "SHA-224's initial state.", words32(&H256_224)),
        ("h256", "SHA-256's initial state.", words32(&H256_256)),
        ("h384", "SHA-384's initial state.", words64(&H512_384)),
        ("h512", "SHA-512's initial state.", words64(&H512_512)),
        (
            "h512_224",
            "SHA-512/224's initial state.",
            words64(&H512_224),
        ),
        (
            "h512_256",
            "SHA-512/256's initial state.",
            words64(&H512_256),
        ),
    ] {
        let name = name.replace("_2", "t2");
        let _ = writeln!(
            out,
            "-- {doc}\n@pub(pkg) def {name} =\n  {}\n",
            long_literal(&value, 96)
        );
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

// --- cases --------------------------------------------------------------------------

/// A small deterministic generator, so that the cases are the same on every run.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        // xorshift64*
        self.0 ^= self.0 >> 12;
        self.0 ^= self.0 << 25;
        self.0 ^= self.0 >> 27;
        self.0.wrapping_mul(0x2545_f491_4f6c_dd1d)
    }

    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }

    fn bytes(&mut self, n: usize) -> Vec<u8> {
        (0..n).map(|_| self.next() as u8).collect()
    }
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// Every digest of `input`, in the order `Tests.mw` lists the functions.
fn digests(input: &[u8]) -> [String; 6] {
    [
        hex(&Sha224::digest(input)),
        hex(&Sha256::digest(input)),
        hex(&Sha384::digest(input)),
        hex(&Sha512::digest(input)),
        hex(&Sha512_224::digest(input)),
        hex(&Sha512_256::digest(input)),
    ]
}

fn cases() -> String {
    let mut rng = Rng(0x5a2_7a4a_c0ff_ee42);
    let mut body = String::new();
    let mut count = 0;
    // Every length up to three 128-byte blocks, so that each padding case is
    // met, and a few long ones.
    for n in (0..=400).chain([1000, 4096, 10000]) {
        let input = rng.bytes(n);
        let split = rng.below(n + 1);
        count += 1;
        bytes(&mut body, &input);
        digits(&mut body, split as u64, 3);
        let whole = digests(&input);
        let mut pieces = Sha256::new();
        pieces.update(&input[..split]);
        pieces.update(&input[split..]);
        assert_eq!(hex(&pieces.finalize()), whole[1]);
        for d in whole {
            text(&mut body, &d);
        }
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "-- GENERATED by scripts/generate.sh from sha2 {UPSTREAM_VERSION}.
-- Do not edit: run the script again instead.
--
-- {count} messages, with the digests the crate gives them, for `Tests.mw`.
--
{HEADER}

-- Each: the message (its hex digits, as a string: a length in 3 base-64 digits
-- and then the text), where to split it for hashing in two pieces (3 digits),
-- and the SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224 and SHA-512/256
-- digests as hex strings.
@cfg(test)
@pub(pkg) def cases =
  {}",
        long_literal(&body, 96)
    );
    out
}
